module Config

type Env =
  | ADMIN_ID
  | APP_NAME
  | BOT_TOKEN
  | BUS_MAP_FILE_ID
  | CONFIGURATION_BUCKET
  | CONFIGURATION_FILE
  | DRIVE_FOLDER_ID
  | GITHUB_ACTION_WORKFLOW_ID
  | GITHUB_APPLICATION_ID
  | GITHUB_APPLICATION_PRIVATE_KEY
  | GITHUB_CLIENT_ID
  | GITHUB_REPOSITORY
  | GITHUB_REPOSITORY_ENVIRONMENT
  | GITHUB_USERNAME
  | GOOGLE_DRIVE_OAUTH_CLIENT_EMAIL
  | GOOGLE_DRIVE_OAUTH_CLIENT_ID
  | GOOGLE_DRIVE_OAUTH_PRIVATE_KEY
  | GOOGLE_DRIVE_OAUTH_PRIVATE_KEY_ID
  | GOOGLE_DRIVE_OAUTH_PROJECT_ID
  | NOTIFY_ENDPOINT
  | TRAIN_MAP_FILE_ID

let get (key: Env): string =
  System.Environment.GetEnvironmentVariable(key.ToString())
